// img2ansi converts an image to terminal art using half-block characters
// with ANSI 24-bit true color.
//
// Usage: go run tools/img2ansi.go <image-path> [width] [--go]
//
// Outputs half-block art to stdout. With --go flag, outputs a Go string literal.
package main

import (
	"fmt"
	"image"
	_ "image/jpeg"
	_ "image/png"
	"math"
	"os"
	"strconv"
	"strings"

	"golang.org/x/image/draw"
)

type rgb struct{ r, g, b uint8 }

func (c rgb) isBackground(bg rgb) bool {
	// Check if this pixel is close to the background color
	dr := int(c.r) - int(bg.r)
	dg := int(c.g) - int(bg.g)
	db := int(c.b) - int(bg.b)
	return (dr*dr + dg*dg + db*db) < 900 // threshold
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: go run tools/img2ansi.go <image> [width] [--go]\n")
		os.Exit(1)
	}

	path := os.Args[1]
	targetWidth := 40
	goMode := false

	for _, arg := range os.Args[2:] {
		if arg == "--go" {
			goMode = true
		} else if n, err := strconv.Atoi(arg); err == nil {
			targetWidth = n
		}
	}

	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	src, _, err := image.Decode(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "decode: %v\n", err)
		os.Exit(1)
	}

	// Resize to target width, maintaining aspect ratio.
	// Terminal characters are ~2:1 tall:wide, and we pack 2 pixels per row
	// with half-blocks, so effective aspect is 1:1 per character cell.
	bounds := src.Bounds()
	srcW := bounds.Dx()
	srcH := bounds.Dy()
	targetHeight := int(math.Round(float64(srcH) * float64(targetWidth) / float64(srcW)))
	// Make height even for half-block pairing
	if targetHeight%2 != 0 {
		targetHeight++
	}

	dst := image.NewRGBA(image.Rect(0, 0, targetWidth, targetHeight))
	draw.CatmullRom.Scale(dst, dst.Bounds(), src, bounds, draw.Over, nil)

	// Sample the top-left corner as background color
	bgR, bgG, bgB, _ := dst.At(0, 0).RGBA()
	bg := rgb{uint8(bgR >> 8), uint8(bgG >> 8), uint8(bgB >> 8)}

	// Build the half-block art
	var lines []string
	for y := 0; y < targetHeight-1; y += 2 {
		var line strings.Builder
		for x := 0; x < targetWidth; x++ {
			tr, tg, tb, _ := dst.At(x, y).RGBA()
			br, bgg, bb, _ := dst.At(x, y+1).RGBA()
			top := rgb{uint8(tr >> 8), uint8(tg >> 8), uint8(tb >> 8)}
			bot := rgb{uint8(br >> 8), uint8(bgg >> 8), uint8(bb >> 8)}

			topBg := top.isBackground(bg)
			botBg := bot.isBackground(bg)

			if topBg && botBg {
				line.WriteString(" ")
			} else if topBg {
				line.WriteString(fmt.Sprintf("\033[38;2;%d;%d;%dm▄\033[0m", bot.r, bot.g, bot.b))
			} else if botBg {
				line.WriteString(fmt.Sprintf("\033[38;2;%d;%d;%dm▀\033[0m", top.r, top.g, top.b))
			} else if top == bot {
				line.WriteString(fmt.Sprintf("\033[38;2;%d;%d;%dm█\033[0m", top.r, top.g, top.b))
			} else {
				line.WriteString(fmt.Sprintf("\033[38;2;%d;%d;%dm\033[48;2;%d;%d;%dm▀\033[0m", top.r, top.g, top.b, bot.r, bot.g, bot.b))
			}
		}
		lines = append(lines, line.String())
	}

	result := strings.Join(lines, "\n")

	if goMode {
		// Output as a Go raw string that can be embedded
		fmt.Println("// Generated by tools/img2ansi.go — do not edit by hand.")
		fmt.Println("package ui")
		fmt.Println()
		fmt.Printf("const mascotArt = `\n%s\n`\n", stripTrailingResets(result))
	} else {
		fmt.Println(result)
	}
}

// stripTrailingResets is a no-op placeholder; raw ANSI is fine in backtick strings.
func stripTrailingResets(s string) string {
	return s
}
